version: "3.8"

services:
  database:
    container_name: mercado_livro
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql

volumes:
  database: { }
