spring:
  profiles:
    active: ${APP_PROFILE:local}
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${JWT_SECRET:MySuperSecretJwt}
  expiration: ${JWT_EXPIRATION:86400000}
